//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5466.
// 
#pragma warning disable 1591

namespace ChinaStockWebService.cn.com.webxml.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ChinaStockWebServiceSoap", Namespace="http://WebXml.com.cn/")]
    public partial class ChinaStockWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getStockImageByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockImageByteByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockImage_kByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockImage_kByteByCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStockInfoByCodeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ChinaStockWebService() {
            this.Url = global::ChinaStockWebService.Properties.Settings.Default.ChinaStockWebService_cn_com_webxml_www_ChinaStockWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getStockImageByCodeCompletedEventHandler getStockImageByCodeCompleted;
        
        /// <remarks/>
        public event getStockImageByteByCodeCompletedEventHandler getStockImageByteByCodeCompleted;
        
        /// <remarks/>
        public event getStockImage_kByCodeCompletedEventHandler getStockImage_kByCodeCompleted;
        
        /// <remarks/>
        public event getStockImage_kByteByCodeCompletedEventHandler getStockImage_kByteByCodeCompleted;
        
        /// <remarks/>
        public event getStockInfoByCodeCompletedEventHandler getStockInfoByCodeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStockImageByCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getStockImageByCode(string theStockCode) {
            this.Invoke("getStockImageByCode", new object[] {
                        theStockCode});
        }
        
        /// <remarks/>
        public void getStockImageByCodeAsync(string theStockCode) {
            this.getStockImageByCodeAsync(theStockCode, null);
        }
        
        /// <remarks/>
        public void getStockImageByCodeAsync(string theStockCode, object userState) {
            if ((this.getStockImageByCodeOperationCompleted == null)) {
                this.getStockImageByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockImageByCodeOperationCompleted);
            }
            this.InvokeAsync("getStockImageByCode", new object[] {
                        theStockCode}, this.getStockImageByCodeOperationCompleted, userState);
        }
        
        private void OngetStockImageByCodeOperationCompleted(object arg) {
            if ((this.getStockImageByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockImageByCodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStockImageByteByCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getStockImageByteByCode(string theStockCode) {
            object[] results = this.Invoke("getStockImageByteByCode", new object[] {
                        theStockCode});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getStockImageByteByCodeAsync(string theStockCode) {
            this.getStockImageByteByCodeAsync(theStockCode, null);
        }
        
        /// <remarks/>
        public void getStockImageByteByCodeAsync(string theStockCode, object userState) {
            if ((this.getStockImageByteByCodeOperationCompleted == null)) {
                this.getStockImageByteByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockImageByteByCodeOperationCompleted);
            }
            this.InvokeAsync("getStockImageByteByCode", new object[] {
                        theStockCode}, this.getStockImageByteByCodeOperationCompleted, userState);
        }
        
        private void OngetStockImageByteByCodeOperationCompleted(object arg) {
            if ((this.getStockImageByteByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockImageByteByCodeCompleted(this, new getStockImageByteByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStockImage_kByCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getStockImage_kByCode(string theStockCode, string theType) {
            this.Invoke("getStockImage_kByCode", new object[] {
                        theStockCode,
                        theType});
        }
        
        /// <remarks/>
        public void getStockImage_kByCodeAsync(string theStockCode, string theType) {
            this.getStockImage_kByCodeAsync(theStockCode, theType, null);
        }
        
        /// <remarks/>
        public void getStockImage_kByCodeAsync(string theStockCode, string theType, object userState) {
            if ((this.getStockImage_kByCodeOperationCompleted == null)) {
                this.getStockImage_kByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockImage_kByCodeOperationCompleted);
            }
            this.InvokeAsync("getStockImage_kByCode", new object[] {
                        theStockCode,
                        theType}, this.getStockImage_kByCodeOperationCompleted, userState);
        }
        
        private void OngetStockImage_kByCodeOperationCompleted(object arg) {
            if ((this.getStockImage_kByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockImage_kByCodeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStockImage_kByteByCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getStockImage_kByteByCode(string theStockCode, string theType) {
            object[] results = this.Invoke("getStockImage_kByteByCode", new object[] {
                        theStockCode,
                        theType});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getStockImage_kByteByCodeAsync(string theStockCode, string theType) {
            this.getStockImage_kByteByCodeAsync(theStockCode, theType, null);
        }
        
        /// <remarks/>
        public void getStockImage_kByteByCodeAsync(string theStockCode, string theType, object userState) {
            if ((this.getStockImage_kByteByCodeOperationCompleted == null)) {
                this.getStockImage_kByteByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockImage_kByteByCodeOperationCompleted);
            }
            this.InvokeAsync("getStockImage_kByteByCode", new object[] {
                        theStockCode,
                        theType}, this.getStockImage_kByteByCodeOperationCompleted, userState);
        }
        
        private void OngetStockImage_kByteByCodeOperationCompleted(object arg) {
            if ((this.getStockImage_kByteByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockImage_kByteByCodeCompleted(this, new getStockImage_kByteByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WebXml.com.cn/getStockInfoByCode", RequestNamespace="http://WebXml.com.cn/", ResponseNamespace="http://WebXml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getStockInfoByCode(string theStockCode) {
            object[] results = this.Invoke("getStockInfoByCode", new object[] {
                        theStockCode});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getStockInfoByCodeAsync(string theStockCode) {
            this.getStockInfoByCodeAsync(theStockCode, null);
        }
        
        /// <remarks/>
        public void getStockInfoByCodeAsync(string theStockCode, object userState) {
            if ((this.getStockInfoByCodeOperationCompleted == null)) {
                this.getStockInfoByCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStockInfoByCodeOperationCompleted);
            }
            this.InvokeAsync("getStockInfoByCode", new object[] {
                        theStockCode}, this.getStockInfoByCodeOperationCompleted, userState);
        }
        
        private void OngetStockInfoByCodeOperationCompleted(object arg) {
            if ((this.getStockInfoByCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStockInfoByCodeCompleted(this, new getStockInfoByCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getStockImageByCodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getStockImageByteByCodeCompletedEventHandler(object sender, getStockImageByteByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStockImageByteByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStockImageByteByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getStockImage_kByCodeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getStockImage_kByteByCodeCompletedEventHandler(object sender, getStockImage_kByteByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStockImage_kByteByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStockImage_kByteByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void getStockInfoByCodeCompletedEventHandler(object sender, getStockInfoByCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStockInfoByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStockInfoByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591