#ifndef GUARD_BEDROCK_CONFIG_PLATEFORM_WINDOWS_H
#define GUARD_BEDROCK_CONFIG_PLATEFORM_WINDOWS_H

#define SMCP_PLATEFORM_NAME_WIN32 "Microsoft Windows 32 bit"
#define SMCP_PLATEFORM_NAME_WIN64 "Microsoft Windows 64 bit"

#ifdef  _M_IX86
#	define SMCP_PLATEFORM_NAME SMCP_PLATEFORM_NAME_WIN32
#elif   _M_AMD64
#	define SMCP_PLATEFORM_NAME SMCP_PLATEFORM_NAME_WIN64
#endif

#define SMCP_PLATEFORM_WINDOWS


//#include <windows.h>

#endif // GUARD_BEDROCK_CONFIG_PLATEFORM_WINDOWS_H
